### ISSUE TITLE
Max Channels?

### ISSUE THREAD

**Issue by zaptrem** [sekiguchi92/SoundSourceSeparation#2]
What are the maximum number of channels allowed for each algorithm?

**Comment by sekiguchi92** [comment]
There is no limitation in theory.
However, when the number of channels is large, some algorithms may be unstable.

**Comment by pfeatherstone** [comment]
How many is large? I'm using 12

**Comment by sekiguchi92** [comment]
Please check my new paper about FastMNMF2 [https://ieeexplore.ieee.org/document/9177266](url).
Even when M=8, the performance of FastMNMF1 is much lower than that of FastMNMF2.
