### ISSUE TITLE
FastMNMF : Memory consumption very large

### ISSUE THREAD

**Issue by pfeatherstone** [sekiguchi92/SoundSourceSeparation#3]
The FastMNMF algorithm uses a lot of memory. A 24s clip at 16kHz with 12 channels (~9.2MB)  requires over 25GB of memory.
Can this be dealt with or do the algorithms require the entire memory loaded up-front?

**Comment by sekiguchi92** [comment]
Please refer to the comment against your question about FastMNMF2.
I will survey about this problem more.
