### ISSUE TITLE
Questions: FastMNMF2, time synchronisation, memory effienciency

### ISSUE THREAD

**Issue by pfeatherstone** [sekiguchi92/SoundSourceSeparation#4]
I have some questions.

1) Is there code for FastMNMF2?

2) There doesn't seem to be any requirements on the individual channels in the input file. Do they need to be time synchronised? Is there any restriction on topology of microphones (where there are situated)? Does this topology need to be known a priori?

3) Do the algorithms need to have oversight of the entire data? Or can audio files be batched into blocks, maybe overlapping, to reduce memory usage? Or will that degrade performance/accuracy?

**Comment by sekiguchi92** [comment]
>1.  Is there code for FastMNMF2?
Currently, no.

> 2. There doesn't seem to be any requirements on the individual channels in the input file. Do they need to be time synchronised? Is there any restriction on topology of microphones (where there are situated)? Does this topology need to be known a priori?
Synchronization is of course necessary, but there is no requirement on microphone array geometry, and pre-information is not required. 

> 3. Do the algorithms need to have oversight of the entire data? Or can audio files be batched into blocks, maybe overlapping, to reduce memory usage? Or will that degrade performance/accuracy?
It's possible to apply FastMNMF2 with a block-wise manner, however  the performance will be lower than the case with the entire data.
And you need to implement it by yourself.
I'd like to try online extension, but I don't know when that will be.

**Comment by pfeatherstone** [comment]
How about FastMNMF and ILRMA, will they substantially degrade if used in a block-wise manner? I have a 24s clip at 16kHz with 12 channels. FastMNMF requires > 25GB of RAM! ILRMA requires a lot less.

**Comment by pfeatherstone** [comment]
Also, do you know what the tolerance is on synchronisation? I'm using multiple microphone arrays and I'm doing my best to start and stop recording at the same (using parallel code and barriers). Then i concatenate the raw channels of all microphone arrays into a single multi-channel WAV file.

**Comment by pfeatherstone** [comment]
i could record the exact timestamps of when each thread starts recording, then do some fractional sample delay filtering to align everything before hitting your code.

**Comment by pfeatherstone** [comment]
Using farrow filters maybe...

**Comment by sekiguchi92** [comment]
I updated FastMNMF. Please check README.md.
By setting new option n_bit to 32, you can reduce memory usage and computational cost,
but I'm not sure whether it works with the number of microphones is large.
And I found why FastMNMF uses a lot of memory, and fixed the problem.

> How about FastMNMF and ILRMA, will they substantially degrade if used in a block-wise manner?

I think so.

> do you know what the tolerance is on synchronisation?

I'm sorry I've never tried source separation using multiple microphone arrays.
