### ISSUE TITLE
Feature request: 32bit support and memory fix for FastFCA2 and FastMNMF2

### ISSUE THREAD

**Issue by pfeatherstone** [sekiguchi92/SoundSourceSeparation#6]
Please

**Comment by pfeatherstone** [comment]
It seems the memory issue that was corrected in FastFCA and FastMNMF has lingered in FastFCA2 and FastMNMF2

**Comment by pfeatherstone** [comment]
I.e. ```return_InverseMatrixCalculationMethod``` is still used in FastFCA2 and FastMNMF2

**Comment by sekiguchi92** [comment]
I mistakenly uploaded those files. Thank you for your information.

**Comment by pfeatherstone** [comment]
@sekiguchi92 Do you not plan on releasing FastFCA2 and FastMNMF2 or are they not ready yet?

**Comment by sekiguchi92** [comment]
I'm still thinking for some reasons.
